# Generated by Django 4.1.5 on 2023-03-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCT', '0003_remove_p_details_p_img4'),
    ]

    operations = [
        migrations.AddField(
            model_name='p_details',
            name='p_filter',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
