# Generated by Django 4.1.5 on 2023-03-15 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCT', '0004_p_details_p_filter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='p_details',
            name='subcat_id',
        ),
        migrations.AddField(
            model_name='p_details',
            name='cat_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='PRODUCT.cat'),
        ),
    ]
