# Generated by Django 4.1.5 on 2023-03-15 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCT', '0005_remove_p_details_subcat_id_p_details_cat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p_details',
            name='cat_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='PRODUCT.cat'),
        ),
    ]
