# Generated by Django 4.1.7 on 2023-03-21 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCT', '0007_remove_p_details_cat_id_p_details_subcat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('Acs_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Acs_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='bag',
            fields=[
                ('bag_id', models.IntegerField(primary_key=True, serialize=False)),
                ('bag_name', models.CharField(max_length=25)),
                ('bag_color', models.CharField(max_length=20)),
                ('bag_brand', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cosmetics',
            fields=[
                ('Csmtc_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Csmtc_price', models.IntegerField()),
                ('Csmtc_brand', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='footwear',
            fields=[
                ('footWear_id', models.IntegerField(primary_key=True, serialize=False)),
                ('footWear_name', models.CharField(max_length=20)),
                ('footWear_color', models.CharField(max_length=20)),
                ('footWear_brand', models.CharField(max_length=20)),
            ],
        ),
    ]
