# Generated by Django 4.1.7 on 2023-03-21 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCT', '0008_accessories_bag_cosmetics_footwear'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bag',
            old_name='bag_brand',
            new_name='purse_brand',
        ),
        migrations.RenameField(
            model_name='bag',
            old_name='bag_color',
            new_name='purse_color',
        ),
        migrations.RenameField(
            model_name='bag',
            old_name='bag_id',
            new_name='purse_id',
        ),
        migrations.RenameField(
            model_name='bag',
            old_name='bag_name',
            new_name='purse_name',
        ),
        migrations.AddField(
            model_name='accessories',
            name='Acs_img',
            field=models.ImageField(null=True, upload_to='Products'),
        ),
        migrations.AddField(
            model_name='accessories',
            name='Acs_img1',
            field=models.ImageField(null=True, upload_to='Products'),
        ),
        migrations.AddField(
            model_name='accessories',
            name='Acs_img2',
            field=models.ImageField(null=True, upload_to='Products'),
        ),
        migrations.AddField(
            model_name='accessories',
            name='Acs_img3',
            field=models.ImageField(null=True, upload_to='Products'),
        ),
        migrations.AddField(
            model_name='accessories',
            name='Acs_type',
            field=models.CharField(choices=[('Neckpiece', 'Neckpiece'), ('Rings', 'Rings'), ('Bangles', 'Bangles'), ('Earings', 'Earings')], default='Neckpiece', max_length=30),
        ),
        migrations.AddField(
            model_name='bag',
            name='purse_img',
            field=models.ImageField(null=True, upload_to='Products'),
        ),
        migrations.AddField(
            model_name='bag',
            name='purse_img1',
            field=models.ImageField(null=True, upload_to='Products'),
        ),
        migrations.AddField(
            model_name='bag',
            name='purse_img2',
            field=models.ImageField(null=True, upload_to='Products'),
        ),
        migrations.AddField(
            model_name='bag',
            name='purse_img3',
            field=models.ImageField(null=True, upload_to='Products'),
        ),
        migrations.AddField(
            model_name='bag',
            name='purse_type',
            field=models.CharField(choices=[('Wallet', 'Wallet'), ('Clutches', 'Clutches'), ('Waistbag', 'Waistbag')], default='Clutches', max_length=30),
        ),
        migrations.AddField(
            model_name='cosmetics',
            name='Csmtc_img',
            field=models.ImageField(null=True, upload_to='Products'),
        ),
        migrations.AddField(
            model_name='cosmetics',
            name='Csmtc_img1',
            field=models.ImageField(null=True, upload_to='Products'),
        ),
        migrations.AddField(
            model_name='cosmetics',
            name='Csmtc_img2',
            field=models.ImageField(null=True, upload_to='Products'),
        ),
        migrations.AddField(
            model_name='cosmetics',
            name='Csmtc_img3',
            field=models.ImageField(null=True, upload_to='Products'),
        ),
        migrations.AddField(
            model_name='cosmetics',
            name='Csmtc_type',
            field=models.CharField(choices=[('Foundation', 'Foundation'), ('Concealer', 'Concealer'), ('Primer', 'Primer'), ('Lipstick', 'Lipstick'), ('Compact', 'Compact')], default='Foundation', max_length=30),
        ),
        migrations.AddField(
            model_name='footwear',
            name='footWear_img',
            field=models.ImageField(null=True, upload_to='Products'),
        ),
        migrations.AddField(
            model_name='footwear',
            name='footWear_img1',
            field=models.ImageField(null=True, upload_to='Products'),
        ),
        migrations.AddField(
            model_name='footwear',
            name='footWear_img2',
            field=models.ImageField(null=True, upload_to='Products'),
        ),
        migrations.AddField(
            model_name='footwear',
            name='footWear_img3',
            field=models.ImageField(null=True, upload_to='Products'),
        ),
        migrations.AddField(
            model_name='footwear',
            name='footwear_type',
            field=models.CharField(choices=[('Slipper', 'Slipper'), ('Heal', 'Heals'), ('Sandals', 'Sandals')], default='Slipper', max_length=30),
        ),
    ]
