# Generated by Django 4.1.7 on 2023-03-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCT', '0009_rename_bag_brand_bag_purse_brand_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accessories',
        ),
        migrations.DeleteModel(
            name='bag',
        ),
        migrations.DeleteModel(
            name='Cosmetics',
        ),
        migrations.DeleteModel(
            name='footwear',
        ),
        migrations.AddField(
            model_name='p_details',
            name='Acs_type',
            field=models.CharField(choices=[('Neckpiece', 'Neckpiece'), ('Rings', 'Rings'), ('Bangles', 'Bangles'), ('Earings', 'Earings')], default='Neckpiece', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='p_details',
            name='Csmtc_type',
            field=models.CharField(choices=[('Foundation', 'Foundation'), ('Concealer', 'Concealer'), ('Primer', 'Primer'), ('Lipstick', 'Lipstick'), ('Compact', 'Compact')], default='Foundation', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='p_details',
            name='footwear_type',
            field=models.CharField(choices=[('Slipper', 'Slipper'), ('Heal', 'Heals'), ('Sandals', 'Sandals')], default='Slipper', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='p_details',
            name='p_brand',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='p_details',
            name='purse_type',
            field=models.CharField(choices=[('Wallet', 'Wallet'), ('Clutches', 'Clutches'), ('Waistbag', 'Waistbag')], default='Clutches', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='p_details',
            name='p_color',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='p_details',
            name='p_desc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='p_details',
            name='p_fabric',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='p_details',
            name='p_filter',
            field=models.CharField(default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='p_details',
            name='p_qty',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='p_details',
            name='p_size',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='p_details',
            name='p_type',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
