# Generated by Django 4.1.7 on 2023-03-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCT', '0011_remove_p_details_subcat_id_p_details_cat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p_details',
            name='Acs_type',
            field=models.CharField(blank=True, choices=[('Neckpiece', 'Neckpiece'), ('Rings', 'Rings'), ('Bangles', 'Bangles'), ('Earings', 'Earings')], default='Neckpiece', max_length=30),
        ),
        migrations.AlterField(
            model_name='p_details',
            name='Csmtc_type',
            field=models.CharField(blank=True, choices=[('Foundation', 'Foundation'), ('Concealer', 'Concealer'), ('Primer', 'Primer'), ('Lipstick', 'Lipstick'), ('Compact', 'Compact')], default='Foundation', max_length=30),
        ),
        migrations.AlterField(
            model_name='p_details',
            name='footwear_type',
            field=models.CharField(blank=True, choices=[('Slipper', 'Slipper'), ('Heal', 'Heals'), ('Sandals', 'Sandals')], default='Slipper', max_length=30),
        ),
        migrations.AlterField(
            model_name='p_details',
            name='p_brand',
            field=models.CharField(blank=True, max_length=20, null='True'),
        ),
        migrations.AlterField(
            model_name='p_details',
            name='p_color',
            field=models.CharField(blank=True, max_length=50, null='True'),
        ),
        migrations.AlterField(
            model_name='p_details',
            name='p_desc',
            field=models.CharField(blank=True, max_length=100, null='True'),
        ),
        migrations.AlterField(
            model_name='p_details',
            name='p_fabric',
            field=models.CharField(blank=True, max_length=30, null='True'),
        ),
        migrations.AlterField(
            model_name='p_details',
            name='p_filter',
            field=models.CharField(blank=True, default=0, max_length=20, null='True'),
        ),
        migrations.AlterField(
            model_name='p_details',
            name='p_img',
            field=models.ImageField(blank=True, null='True', upload_to='Products'),
        ),
        migrations.AlterField(
            model_name='p_details',
            name='p_img1',
            field=models.ImageField(blank=True, null='True', upload_to='Products'),
        ),
        migrations.AlterField(
            model_name='p_details',
            name='p_img2',
            field=models.ImageField(blank=True, null='True', upload_to='Products'),
        ),
        migrations.AlterField(
            model_name='p_details',
            name='p_img3',
            field=models.ImageField(blank=True, null='True', upload_to='Products'),
        ),
        migrations.AlterField(
            model_name='p_details',
            name='p_qty',
            field=models.IntegerField(blank=True, null='True'),
        ),
        migrations.AlterField(
            model_name='p_details',
            name='p_size',
            field=models.CharField(blank=True, max_length=30, null='True'),
        ),
        migrations.AlterField(
            model_name='p_details',
            name='p_type',
            field=models.CharField(blank=True, max_length=30, null='True'),
        ),
        migrations.AlterField(
            model_name='p_details',
            name='purse_type',
            field=models.CharField(blank=True, choices=[('Wallet', 'Wallet'), ('Clutches', 'Clutches'), ('Waistbag', 'Waistbag')], default='Clutches', max_length=30),
        ),
    ]
