# Generated by Django 4.1.7 on 2023-03-21 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCT', '0012_alter_p_details_acs_type_alter_p_details_csmtc_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='p_details',
            name='subcat_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='PRODUCT.subcat'),
        ),
    ]
