# Generated by Django 4.1.7 on 2023-03-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCT', '0015_remove_p_details_cat_id_p_details_subcat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p_details',
            name='p_type',
            field=models.CharField(blank=True, choices=[('Kurti', 'Kurti'), ('Kurti Set', 'Kurti Set'), ('Lehenga', 'Lehenga'), ('Dress', 'Dress'), ('Cosmetic', 'Cosmetic'), ('Footwear', 'Footwear'), ('Bags', 'Bags')], default='Kurti', max_length=30),
        ),
        migrations.AlterField(
            model_name='subcat',
            name='subcat_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
