# Generated by Django 4.1.7 on 2023-03-22 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCT', '0016_alter_p_details_p_type_alter_subcat_subcat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='cat_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='p_details',
            name='offer_id',
            field=models.ForeignKey(blank=True, default=0, null='True', on_delete=django.db.models.deletion.SET_DEFAULT, to='PRODUCT.offer'),
        ),
        migrations.AlterField(
            model_name='subcat',
            name='subcat_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
