# Generated by Django 4.1.5 on 2023-02-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('message', models.TextField(max_length=300)),
            ],
        ),
    ]
