# Generated by Django 4.1.7 on 2023-03-21 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DASHBOARD', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_details',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer_details',
            name='cust_phoneno',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='customer_details',
            name='cust_postcode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='customer_details',
            name='cust_state',
            field=models.CharField(max_length=50),
        ),
    ]
