# Generated by Django 4.1.5 on 2023-03-13 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='user',
            new_name='user_id',
        ),
    ]
